[package]
name = "zing_game"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.24"
strum_macros = "0.24"
rand = "0.8.5"
itertools = "0.10.5"
serde = { version = "1.0", features = ["derive"] }
