[package]
name = "zing_game"
version = "0.1.0"
edition = "2021"
description = "card game logic for `Zing`, minimal dependencies (no UI or networking)"
repository = "https://github.com/hmeine/zing-rs"
license = "MIT"

[dependencies]
strum = "0.28.0"
strum_macros = "0.28.0"
rand = "0.10.2"
itertools = "0.15.0"
serde = { version = "1.0.229", features = ["derive"] }
bevy_reflect = "0.19.1"
