[package]
name = "zing_server"
version = "0.1.0"
edition = "2021"

[dependencies]
zing_game = { path = "../zing-game" }

axum = { version = "0.5.17", features = ["ws"] }
chrono = "0.4.23"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
async-trait = "0.1"
tower-cookies = "0.7.0"
cookie = "0.16.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8.5"
serde = "1.0.147"
serde_json = "1.0"
