//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::game_results::Entity as GameResults;
pub use super::table::Entity as Table;
pub use super::table_join::Entity as TableJoin;
pub use super::user::Entity as User;
