//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::table_join::Entity")]
    TableJoin,
}

impl Related<super::table_join::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableJoin.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::table_join::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::table_join::Relation::Table.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
