//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub token: String,
    pub name: String,
    pub logged_in: bool,
    pub last_seen: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::table_join::Entity")]
    TableJoin,
}

impl Related<super::table_join::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableJoin.def()
    }
}

impl Related<super::table::Entity> for Entity {
    fn to() -> RelationDef {
        super::table_join::Relation::Table.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::table_join::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
