[package]
name = "zing-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.24"
strum_macros = "0.24"
rand = "0.8.5"
itertools = "0.10.5"
zing_game = { path = "../zing-game" }

bevy = { version = "0.8" }
bevy_tweening = "0.5"
